name: Coinz
main: dev.mCraft.Coinz.Coinz
version: 0.0.9
depend: [Spout, Vault]
permissions:
  coinz.craft.teller:
    description: Gives permission to craft a teller.
    default: false
  coinz.craft.vault
    description: Gives permission to craft a vault.
    default: true
  coinz.craft.goldcoin:
    description: Allows the player to craft gold coins from gold nuggets.
    default: false