main: dev.mCraft.Coinz.Coinz
name: Coinz
description: A spout plugin that adds a physical currency to the game.
version: 0.0.9
depend: [Spout, Vault]
commands:
  test:
    description: Testing
    usage: |
      /<command>
permissions:
  coinz.*:
    description: Gives player all permissions.
    default: false
    children:
      coinz.craft.teller: true
      coinz.craft.vault: true
      coinz.craft.goldcoin: true
  coinz.craft.teller:
    description: Allows the player to craft a teller.
    default: false
  coinz.craft.vault:
    description: Allows the player to craft a vault.
    default: true
  coinz.craft.goldcoin:
    description: Allows the player to craft a goldcoin from nuggets.
    default: false